var countrydata = {
    "flags": {
        "ISR": "flags/israel.webp",
        "PAL": "flags/palestine.webp",
        "SYR": "flags/syria.webp",
        "ISI": "flags/isis.png",
        "GLOBE": "flags/un.webp",
        "ALQ": "flags/alqaida.png",
        "KUR": "flags/kurdistan.webp",
        "TUR": "flags/turkiye.png",
        "ROJ": "flags/rojava.png",
        "GRE": "flags/greek.webp",
        "CYP": "flags/cyrpurs.webp",
        "NCY": "flags/ncy.svg",
        "ARM": "flags/armenia.webp",
        "AZR": "flags/azerbaijan.png",
        "SER": "flags/serbia.png",
        "KOS": "flags/ksovo.png",
        "RUS": "flags/russia.png",
        "UKR": "flags/ukraine.webp",
        "SPR": "flags/spain.png",
        "CAT": "flags/catalonia.png",
        "BSQ": "flags/basque.png",
        "MOR": "flags/mor.png",
        "FRA": "flags/france.png",
        "BRI": "flags/breton.png",
        "COR": "flags/corsica.png",
        "ENG": "flags/britannia.png",
        "EUR": "flags/europa.png",
        "SCO": "flags/scotland.png",
        "WAL": "flags/wales.png",
        "NEN": "flags/nen.png",
        "IRE": "flags/ireland.png",
        "ENGIRE": "flags/engire.png",
        "ULS": "flags/ulster.png",
        "ARG": "flags/arg.png",
        "SDR": "flags/sahara.png",
        "IRN": "flags/irania.png",
        "SAU": "flags/saudi.png",
        "SPC": "flags/houthi.png",
        "PLC": "flags/yemen.png",
        "IND": "flags/india.png",
        "PAK": "flags/pakistan.png",
        "MOL": "flags/moldova.png",
        "TRA": "flags/transnistria.png",
        "ROK": "flags/korean.png",
        "PRK": "flags/peoples korea.png",
        "CHI": "flags/china.png",
        "TIB": "flags/tibet.png",
        "XIN": "flags/turkeystan.png",
        "HKG": "flags/hong kong.png",
        "ROC": "flags/roc.png",
        "JAP": "flags/japanese.png",
        "SCSD": "flags/asean.png",
        "GEO": "flags/georgia.png",
        "SOE": "flags/sos.png",
        "ABK": "flags/abkhazia.png",
        "SOM": "flags/somalia.png",
        "SML": "flags/somaliland.png",
        "CAN": "flags/canada.png",
        "QUE": "flags/french canada.png",
        "USA": "flags/USA USA.png",
        "CUB": "flags/cuban.png",
        "TLB": "flags/+.png",
        "IRA": "flags/so true.png",
        "BLR": "flags/luka.png",
        "BLO": "flags/anti luka.png",
        "SYO": "flags/syrian opposition.png",
        "RUO": "flags/wbw.png",
        "ETH": "flags/ethiopia.png",
        "TIG": "flags/tigray.png",
        "BOS": "flags/bos.png",
        "SRP": "flags/srpska.png",
        "IRR": "flags/irish republic.png",
        "OCC": "flags/occitan.png",
        "TEX": "flags/texas.png",
        "CSA": "flags/csa.png",
        "INM": "flags/inm.png",
        "MAN": "flags/manchu.png",
        "CHE": "flags/chech.png",
        "NAX": "flags/naxal.png",
        "PRU": "flags/peru.png",
        "SHP": "flags/boiled babies.png",
        "VEG": "flags/veg.png",
        "VEM": "flags/vem.png",
        "FTH": "flags/fatah.png",
        "HMS": "flags/hamas.png",
        "MYA": "flags/myanmar.png",
        "WAA": "flags/waaa.png",
        "TAI": "flags/taiwan.png",
        "EGY": "flags/egypt.png",
        "SUD": "flags/sudan.png",
        "SSD": "flags/south sudan.png",
        "TUA": "flags/tuareg.png",
        "MLI": "flags/mali.png",
        "ALG": "flags/algeria.png",
        "NGA": "flags/nigeria.png",
        "BIA": "flags/biafra.png",
        "CMR": "flags/cameroon.png",
        "AMB": "flags/ambazonia.png",
        "KAT": "flags/katanga.png",
        "DRC": "flags/drc.png",
        "RHO": "flags/rhodesia.png",
        "ZIM": "flags/zimbabwe.png",
        "ERI": "flags/eritrea.png",
        "PNG": "flags/png.png",
        "BOU": "flags/bougainville.png",
        "HVR": "flags/havering.png",
        "GER": "flags/germany.png",
        "REI": "flags/reichsburger.png",
        "PET": "flags/petoria.png",
        "MYM-NUG": "flags/myanmar nug.png",
        "MYM-SAC": "flags/tatmadaw.png",
        "UFEFCF": "flags/UFEFCF.png",
        "MAGHREB": "flags/MAGHREB.jpg",
        "MEX": "flags/mexico.png",
        "CARTELS": "flags/CARTELS.png",
        "COL": "flags/COL.png",
        "COL-RW": "flags/COL-RW.png",
        "COL-GU": "flags/COL-GU.png",
        "UGA": "flags/UGA.png",
        "ADF": "flags/ADF.png",
        "CRN": "flags/CRN.png",
        "GER-KR": "flags/GER-KR.png",
        "AHE": "flags/AHE.png",
        "BUL": "flags/BUL.png",
        "SOV": "flags/SOV.png",
        "GER-33": "flags/nazi.png",
        "ITA-WW2": "flags/italy-ww2.png",
        "BRZ-em": "flags/brazil-empire.png",
        "POR-uk": "flags/portugal-uk.png",

        "ENG-william-rufus": "flags/ENG-william-rufus.jpg",
        "ENG-robert-curthose": "flags/ENG-robert-curthose.jpg",
        "ENG-stephen-blois": "flags/ENG-stephen-blois.webp",
        "ENG-empress-matilda": "flags/ENG-empress-matilda.jpg",
        "ENG-angevin": "flags/ENG-angevin.png",
        "ENG-young-henry": "flags/ENG-young-henry.jpg",
        "ENG-kingdom-old": "flags/ENG-angevin.png",
        "ENG-army-of-god": "flags/ENG-army-of-god.png",
        "ENG-barons": "flags/ENG-barons.png",
        "ENG-marcher-lords": "flags/ENG-marcher-lords.png",
        "ENG-lancaster": "flags/ENG-lancaster.png",
        "ENG-york": "flags/ENG-york.png",
        "ENG-royalists": "flags/ENG-royalists.png",
        "ENG-parliamentarians": "flags/ENG-parliamentarians.png",
        "ENG-scotland": "flags/ENG-scotland.png",
        "ENG-commonwealth": "flags/ENG-commonwealth.png",
        "ENG-james": "flags/ENG-royalists.png",
        "ENG-dutch": "flags/ENG-dutch.png",
        "IRN-shah": "flags/IRN-shah.png",
        "AZR-pop-gov": "flags/AZR-pop-gov.png",
        "MAHABAD": "flags/MAHABAD.png",
        "TUDEH": "flags/Red flag.png",
        "GRE-kingdom": "flags/GRE-kingdom.png",
        "GRE-communist": "flags/GRE-communist.png",
        "CCP": "flags/CCP.png",
        "CZE-NSP": "flags/CZE-NSP.png",
        "CZE-KSC": "flags/CZE-KSC.png",
        "ARAB": "flags/ARAB.png",
        "EGY-kingdom": "flags/EGY-kingdom.png",
        "EGY-officers": "flags/EGY-officers.png",
        "FKH-kor": "flags/FKH-kor.webp",
        "FKH-fin": "flags/FKH-fin.webp",
        "NATO": "flags/NATO.png",
        "ALIEN": "flags/ALIEN.png",
        "1984-oc": "flags/1984-oc.gif",
        "1984-eu": "flags/1984-eu.webp",
        "1984-ea": "flags/1984-ea.png",
        "GAL-republic": "flags/galactic-republic.png",
        "GAL-cis": "flags/cis.webp",
        "GAL-empire": "flags/galactic-empire.png",
        "GAL-rebels": "flags/rebel-alliance.png",
        "USA-revolution": "flags/USA-revolution.png",
        "USA-15": "flags/USA-15.png",
        "USA-cw": "flags/USA-cw.png",
        "GBR": "flags/GBR.png",
        "USA-biden": "flags/USA-biden.png",
        "USA-antifa": "flags/USA-antifa.png",
        "USA-trump": "flags/USA-trump.png",
        "USA-proud-boys": "flags/USA-proud-boys.png",
        "USA-cal": "flags/USA-cal.png",
        "USA-awd": "flags/USA-awd.png",
        "USA-napsr": "flags/USA-napsr.png",
        "DNR": "flags/DNR.png",
        "LNR": "flags/LNR.png",
        "ZNR": "flags/ZNR.png",        
        "KNR": "flags/KNR.png",        
    },
    "names": {
        "DNR": "Donetsk People's Republic",
        "LNR": "Lugansk People's Republic",
        "ZNR": "Zaporozhye People's Republic",        
        "KNR": "Kherson People's Republic",
        "USA-biden": "Bidenistas",
        "USA-antifa": "Antifa",
        "USA-trump": "Trump Train",
        "USA-proud-boys": "Proud Boys",
        "USA-cal": "Red California",
        "USA-awd": "Atomwaffen Division",
        "USA-napsr": "New Afrikan People's Socialist Republic",
        "GBR": "Great Britain",
        "USA-revolution": "United States",
        "USA-15": "United States",
        "USA-cw": "United States",
        "GAL-republic": "Galactic Republic",
        "GAL-cis": "Confederacy of Independent Systems",
        "GAL-empire": "Galactic Empire",
        "GAL-rebels": "Rebel Alliance",
        "1984-oc": "Oceania",
        "1984-eu": "Eurasia",
        "1984-ea": "Eastasia",
        "ALIEN": "Aliens",
        "NATO": "North Atlantic Treaty Organisation",
        "FKH-kor": "Great Hwan Empire",
        "FKH-fin": "Proto-Finnic Holy Roman Khaganate",
        "EGY-kingdom": "Kingdom of Egypt",
        "EGY-officers": "Free Officers Movement",
        "ARAB": "Arab League",
        "CZE-NSP": "President of Czechoslovakia",
        "CZE-KSC": "Communist Party of Czechoslovakia",
        "CCP": "Chinese Communist Party",
        "GRE-kingdom": "Kingdom of Greece",
        "GRE-communist": "Provisional Democratic Government",
        "IRN-shah": "Imperial Iran",
        "AZR-pop-gov": "Azerbaijan People's Government",
        "MAHABAD": "Republic of Mahabad",
        "TUDEH": "Tudeh Military Network",
        "ENG-william-rufus": "William Rufus",
        "ENG-robert-curthose": "Robert Curthose",
        "ENG-stephen-blois": "Stephen Blois",
        "ENG-empress-matilda": "Empress Matilda",
        "ENG-angevin": "Henry II",
        "ENG-young-henry": "Henry the Young King",
        "ENG-kingdom-old": "Kingdom of England",
        "ENG-army-of-god": "Army of God and the Holy Church",
        "ENG-barons": "Simon de Montfort",
        "ENG-marcher-lords": "Contrariants",
        "ENG-lancaster": "House of Lancaster",
        "ENG-york": "House of York",
        "ENG-royalists": "Royalists",
        "ENG-parliamentarians": "Parliamentarians",
        "ENG-scotland": "Scotland",
        "ENG-commonwealth": "Commonwealth of England",
        "ENG-james": "James II and VII",
        "ENG-dutch": "Dutch Republic",

        "BRZ-em": "Empire of Brazil",
        "POR-uk": "United Kingdom of Portugal, Brazil and the Algarves",
        "ITA-WW2": "Fascist Italy",
        "GER-33": "Nazi Germany",
        "SOV": "Soviet Union",
        "GER-KR": "German Empire",
        "AHE": "Austro-Hungarian Empire",
        "BUL": "Bulgaria",
        "CRN": "Cornwall",
        "UGA": "Uganda",
        "ADF": "Allied Democratic Forces",
        "COL": "Colombia",
        "COL-RW": "Right-Wing Paramilitaries and Cartels",
        "COL-GU": "Guerrillas",
        "MEX": "Mexico",
        "CARTELS": "Mexican Cartels",
        "MAGHREB": "Maghreb",
        "UFEFCF": "United Front of Ethiopian Federalist and Confederalist Forces",
        "MYM-NUG": "National Unity Government",
        "MYM-SAC": "State Administration Council",
        "ISR": "Israel",
        "PAL": "Palestine",
        "SYR": "Syrian Arab Republic",
        "ISI": "Islamic State",
        "GLOBE": "The World",
        "ALQ": "Al Qaeda",
        "KUR": "Kurdistan",
        "TUR": "Turkey",
        "ROJ": "Rojava (AANES)",
        "GRE": "Greece",
        "CYP": "Cyprus",
        "NCY": "Northern Cyprus",
        "ARM": "Armenia",
        "AZR": "Azerbaijan",
        "SER": "Serbia",
        "KOS": "Kosovo",
        "RUS": "Russia",
        "UKR": "Ukraine",
        "SPR": "Spain",
        "CAT": "Catalonia",
        "BSQ": "Basque",
        "MOR": "Morocco",
        "FRA": "France",
        "BRI": "Brittany",
        "COR": "Corsica",
        "ENG": "United Kingdom",
        "EUR": "European Union",
        "SCO": "Scotland",
        "WAL": "Wales",
        "NEN": "Northern England",
        "IRE": "Republic of Ireland",
        "ENGIRE": "United Kingdom or Ireland",
        "ULS": "Ulster",
        "ARG": "Argentina",
        "SDR": "Sahrawi Arab Democratic Republic",
        "IRN": "Iran",
        "SAU": "Saudi Arabia",
        "SPC": "Supreme Political Council (Houthi)",
        "PLC": "Presidential Leadership Council (Pro-Hadi/Alimi)",
        "IND": "India",
        "PAK": "Pakistan",
        "MOL": "Moldova",
        "TRA": "Transnistria",
        "ROK": "Republic of Korea (South Korea)",
        "PRK": "Democratic People's Republic of Korea (North Korea)",
        "CHI": "China",
        "TIB": "Tibet",
        "XIN": "East Turkestan",
        "HKG": "Hong Kong",
        "ROC": "Republic of China",
        "JAP": "Japan",
        "SCSD": "Not China",
        "GEO": "Georgia",
        "SOE": "South Ossetia",
        "ABK": "Abkhazia",
        "SOM": "Somalia",
        "SML": "Somaliland",
        "CAN": "Canada",
        "QUE": "Quebec",
        "USA": "United States",
        "CUB": "Cuba",
        "TLB": "Taliban",
        "IRA": "National Resistance Council",
        "BLR": "Belarus",
        "BLO": "Belarusian Opposition",
        "SYO": "Syrian Opposition",
        "RUO": "Russian Opposition",
        "ETH": "Ethiopia",
        "TIG": "Tigray",
        "BOS": "Bosnia",
        "SRP": "Srpska",
        "IRR": "Irish Republic",
        "OCC": "Occitania",
        "TEX": "Texas",
        "CSA": "Confederate States",
        "INM": "Inner Mongolia",
        "MAN": "Manchuria",
        "CHE": "Chechnya",
        "NAX": "Naxalites",
        "PRU": "Peru",
        "SHP": "Shining Path",
        "VEG": "Guaidó Government",
        "VEM": "Maduro Government",
        "FTH": "Fatah",
        "HMS": "Hamas",
        "TAI": "Taiwan",
        "MYA": "Myanmar",
        "WAA": "Wa State",
        "EGY": "Egypt",
        "SUD": "Sudan",
        "SSD": "South Sudan",
        "TUA": "Tuaregs",
        "MLI": "Mali",
        "ALG": "Algeria",
        "NGA": "Nigeria",
        "BIA": "Biafra",
        "CMR": "Cameroon",
        "AMB": "Ambazonia",
        "KAT": "Katanga",
        "DRC": "Democratic Republic of the Congo",
        "RHO": "Rhodesia",
        "ZIM": "Zimbabwe",
        "ERI": "Eritrea",
        "PNG": "Papau New Guinea",
        "BOU": "Bougainville",
        "HVR": "Havering",
        "GER": "Germany",
        "REI": "Reichsbürger Movement",
        "PET": "Petoria"
    }
}