var countrydata = {
    "flags": {
        "ISR": "flags/israel.webp",
        "PAL": "flags/palestine.webp",
        "SYR": "flags/syria.webp",
        "ISI": "flags/isis.png",
        "GLOBE": "flags/un.webp",
        "ALQ": "flags/alqaida.png",
        "KUR": "flags/kurdistan.webp",
        "TUR": "flags/turkiye.png",
        "ROJ": "flags/rojava.png",
        "GRE": "flags/greek.webp",
        "CYP": "flags/cyrpurs.webp",
        "NCY": "flags/ncy.svg",
        "ARM": "flags/armenia.webp",
        "AZR": "flags/azerbaijan.png",
        "SER": "flags/serbia.png",
        "KOS": "flags/ksovo.png",
        "RUS": "flags/russia.png",
        "UKR": "flags/ukraine.webp",
        "DNR": "flags/donetsk.png",
        "LNR": "flags/luhansk.png",
        "SPR": "flags/spain.png",
        "CAT": "flags/catalonia.png",
        "BSQ": "flags/basque.png",
        "MOR": "flags/mor.png",
        "FRA": "flags/france.png",
        "BRI": "flags/breton.png",
        "COR": "flags/corsica.png",
        "ENG": "flags/britannia.png",
        "EUR": "flags/europa.png",
        "SCO": "flags/scotland.png",
        "WAL": "flags/wales.png",
        "NEN": "flags/nen.png",
        "IRE": "flags/ireland.png",
        "ENGIRE": "flags/engire.png",
        "ULS": "flags/ulster.png",
        "ARG": "flags/arg.png",
        "SDR": "flags/sahara.png",
        "IRN": "flags/irania.png",
        "SAU": "flags/saudi.png",
        "SPC": "flags/houthi.png",
        "PLC": "flags/yemen.png",
        "IND": "flags/india.png",
        "PAK": "flags/pakistan.png",
        "MOL": "flags/moldova.png",
        "TRA": "flags/transnistria.png",
        "ROK": "flags/korean.png",
        "PRK": "flags/peoples korea.png",
        "CHI": "flags/china.png",
        "TIB": "flags/tibet.png",
        "XIN": "flags/turkeystan.png",
        "HKG": "flags/hong kong.png",
        "ROC": "flags/roc.png",
        "JAP": "flags/japanese.png",
        "SCSD": "flags/asean.png",
        "GEO": "flags/georgia.png",
        "SOE": "flags/sos.png",
        "ABK": "flags/abkhazia.png",
        "SOM": "flags/somalia.png",
        "SML": "flags/somaliland.png",
        "CAN": "flags/canada.png",
        "QUE": "flags/french canada.png",
        "USA": "flags/USA USA.png",
        "CUB": "flags/cuban.png",
        "TLB": "flags/+.png",
        "IRA": "flags/so true.png",
        "BLR": "flags/luka.png",
        "BLO": "flags/anti luka.png",
        "SYO": "flags/syrian opposition.png",
        "RUO": "flags/wbw.png",
        "ETH": "flags/ethiopia.png",
        "TIG": "flags/tigray.png",
        "BOS": "flags/bos.png",
        "SRP": "flags/srpska.png"
    },
    "names": {
        "ISR": "Israel",
        "PAL": "Palestine",
        "SYR": "Syrian Arab Republic",
        "ISI": "Islamic State",
        "GLOBE": "The World",
        "ALQ": "Al Qaeda",
        "KUR": "Kurdistan",
        "TUR": "Turkey",
        "ROJ": "Rojava (AANES)",
        "GRE": "Greece",
        "CYP": "Cyprus",
        "NCY": "Northern Cyprus",
        "ARM": "Armenia",
        "AZR": "Azerbaijan",
        "SER": "Serbia",
        "KOS": "Kosovo",
        "RUS": "Russia",
        "UKR": "Ukraine",
        "DNR": "Donetsk People's Republic",
        "LNR": "Luhansk People's Republic",
        "SPR": "Spain",
        "CAT": "Catalonia",
        "BSQ": "Basque",
        "MOR": "Morocco",
        "FRA": "France",
        "BRI": "Brittany",
        "COR": "Corsica",
        "ENG": "United Kingdom",
        "EUR": "European Union",
        "SCO": "Scotland",
        "WAL": "Wales",
        "NEN": "Northern England",
        "IRE": "Republic of Ireland",
        "ENGIRE": "United Kingdom or Ireland",
        "ULS": "Ulster",
        "ARG": "Argentina",
        "SDR": "Sahrawi Arab Democratic Republic",
        "IRN": "Iran",
        "SAU": "Saudi Arabia",
        "SPC": "Supreme Political Council (Houthi)",
        "PLC": "Presidential Leadership Council (Pro-Hadi/Alimi)",
        "IND": "India",
        "PAK": "Pakistan",
        "MOL": "Moldova",
        "TRA": "Transnistria",
        "ROK": "Republic of Korea (South Korea)",
        "PRK": "Democratic People's Republic of Korea (North Korea)",
        "CHI": "China",
        "TIB": "Tibet",
        "XIN": "East Turkestan",
        "HKG": "Hong Kong",
        "ROC": "Taiwan",
        "JAP": "Japan",
        "SCSD": "Not China",
        "GEO": "Georgia",
        "SOE": "South Ossetia",
        "ABK": "Abkhazia",
        "SOM": "Somalia",
        "SML": "Somaliland",
        "CAN": "Canada",
        "QUE": "Quebec",
        "USA": "United States",
        "CUB": "Cuba",
        "TLB": "Taliban",
        "IRA": "National Resistance Council",
        "BLR": "Belarus",
        "BLO": "Belarusian Opposition",
        "SYO": "Syrian Opposition",
        "RUO": "Russian Opposition",
        "ETH": "Ethiopia",
        "TIG": "Tigray",
        "BOS": "Bosnia",
        "SRP": "Srpska"
    }
}